[package]
name = "demo"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.86"
keep_a_changelog_file = { path = ".." }
serde-wasm-bindgen = "0.6.5"
serde = { version = "1.0.217", features = ["derive"] }
